dev_alias_as "pnpm" "pn" "run"
alias pn-cf="pnpm config"
alias pn-i="pnpm install"
alias pn-ui="pnpm uninstall"
alias pn-cr="pnpm create"
alias pn-u="pnpm update"
alias pn-u-i="pnpm update --interactive"
alias pn-a="pnpm add"
alias pn-rm="pnpm remove"
alias pn-ot="pnpm outdated"
alias pn-dx="pnpm dlx"
alias pn-e="pnpm exec"
alias pn-d="pnpm run dev"
alias pn-cln="pnpm clean"
alias pn-s-p="pnpm store prune"
