alias op="open"
alias op-f="open ."
alias op-s="open -b com.apple.systempreferences"
alias op-st="open -a 'Stickies'"
alias op-o="open -a 'Obsidian'"
alias op-t="open -na Terminal"
alias op-c="open -a 'Google Chrome'"
alias op-cc="open -a 'Google Chrome' 'https://chat.openai.com/'"
alias op-cn="open -a 'Google Chrome' 'https://notebooklm.google.com/'"
alias op-cgm="open -a 'Google Chrome' 'https://gemini.google.com/app?hl=ja'"
alias op-cg="open -a 'Google Chrome' 'https://github.com/akitorahayashi'"
alias op-cj="open -a 'Google Chrome' 'https://jules.google.com/task'"
