import { createHash } from 'node:crypto';
import { chmod, readFile, stat } from 'node:fs/promises';
import { ProvisioningError } from '../errors';
import { isNotFound } from '../host/absence';
import { replaceFileAtomically } from '../host/atomic-file';
import { runProcessStep } from '../host/command-run';
import type { Context } from '../host/context';
import { downloadOverHttps } from '../host/https-download';
import {
  isRecord,
  requireExactKeys,
  requireRecord,
  requireUniqueBy,
} from '../host/parse';
import { loadYaml } from '../host/yaml';

/**
 * A prebuilt CLI binary distributed through GitHub Releases. `repo` is
 * `owner/name`; the release asset is named `<name>-<os>-<arch>`. `private`
 * selects an authenticated `gh release download` over an anonymous `curl`, the
 * only difference being the fetch mechanism.
 */
export interface ReleaseBinary {
  readonly name: string;
  readonly repo: string;
  readonly tag: string;
  readonly private?: boolean;
}

export const releaseArchitectures = ['aarch64', 'x86_64'] as const;
export type ReleaseArch = (typeof releaseArchitectures)[number];
export type ReleaseAssetKey = `darwin-${ReleaseArch}`;

/** The reviewed SHA-256 digest of one release asset. */
export interface ReleaseDigest {
  readonly asset: ReleaseAssetKey;
  readonly sha256: string;
}

interface ReleaseLockEntry {
  readonly name: string;
  readonly repo: string;
  readonly tag: string;
  readonly assets: Readonly<Record<string, ReleaseDigest>>;
}

/**
 * The digest lock generated by `bun run lock`: for every manifest entry, the
 * SHA-256 of each architecture's release asset at lock time. Provisioning
 * refuses bytes that do not match, so adopting a new release is a reviewed
 * change to this file rather than whatever the remote serves at install time.
 */
export interface ReleaseLock {
  readonly binaries: readonly ReleaseLockEntry[];
}

// Release fields flow into a tool's argument DSL: `name` becomes the `gh
// release download --pattern` glob and part of the public download URL, `tag`
// is passed positionally to `gh` and into the URL path, and `repo` is both a
// `--repo` value and a URL segment. Validate the repo-owned manifest against
// explicit character sets (as `brew/install.ts` does for Homebrew tokens) so a
// glob metacharacter cannot match a different asset and a leading '-' cannot
// parse as a flag.
const SAFE_ASSET_NAME = /^[A-Za-z0-9._+][A-Za-z0-9._+-]*$/;
const SAFE_TAG = /^[A-Za-z0-9._+][A-Za-z0-9._+-]*$/;
const SAFE_REPO = /^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/;
const SHA256 = /^[0-9a-f]{64}$/;

/** The release asset name `<name>-darwin-<arch>` for one binary and architecture. */
export function releaseAssetName(
  binary: ReleaseBinary,
  arch: ReleaseArch,
): string {
  return `${binary.name}-${OS}-${arch}`;
}

/** The digest lock's key, a `.lock.yml` sibling of the binaries manifest key. */
export function releaseLockKey(configKey: string): string {
  return configKey.replace(/\.ya?ml$/, '.lock.yml');
}

export function parseReleaseBinaries(
  raw: string,
  path: string,
): ReleaseBinary[] {
  const parsed = requireRecord(
    loadYaml(raw, path),
    `Release binaries manifest ${path}`,
  );
  requireExactKeys(parsed, ['binaries'], `Release binaries manifest ${path}`);
  if (!Array.isArray(parsed['binaries'])) {
    throw new ProvisioningError(
      `Release binaries manifest must contain a binaries sequence: ${path}`,
    );
  }
  const binaries = parsed['binaries'].map((entry: unknown, index: number) => {
    if (!isRecord(entry)) {
      throw new ProvisioningError(
        `Invalid release binaries manifest entry ${index + 1}: entry must be a mapping.`,
      );
    }
    requireExactKeys(
      entry,
      ['name', 'repo', 'tag', 'private'],
      `Invalid release binaries manifest entry ${index + 1}`,
    );
    if (typeof entry['name'] !== 'string' || entry['name'].length === 0) {
      throw new ProvisioningError(
        `Invalid release binaries manifest entry ${index + 1}: 'name' must be a non-empty string.`,
      );
    }
    if (typeof entry['repo'] !== 'string' || entry['repo'].length === 0) {
      throw new ProvisioningError(
        `Invalid release binaries manifest entry ${index + 1} ('${entry['name']}'): 'repo' must be a non-empty string.`,
      );
    }
    if (typeof entry['tag'] !== 'string' || entry['tag'].length === 0) {
      throw new ProvisioningError(
        `Invalid release binaries manifest entry ${index + 1} ('${entry['name']}'): 'tag' must be a non-empty string.`,
      );
    }
    if (
      entry['private'] !== undefined &&
      typeof entry['private'] !== 'boolean'
    ) {
      throw new ProvisioningError(
        `Invalid release binaries manifest entry ${index + 1} ('${entry['name']}'): 'private' must be a boolean.`,
      );
    }
    if (!SAFE_ASSET_NAME.test(entry['name'])) {
      throw new ProvisioningError(
        `Invalid release binaries manifest entry ${index + 1} ('${entry['name']}'): 'name' may contain only letters, digits, and ._+- and must not start with '-'.`,
      );
    }
    if (!SAFE_TAG.test(entry['tag'])) {
      throw new ProvisioningError(
        `Invalid release binaries manifest entry ${index + 1} ('${entry['name']}'): 'tag' may contain only letters, digits, and ._+- and must not start with '-'.`,
      );
    }
    if (!SAFE_REPO.test(entry['repo'])) {
      throw new ProvisioningError(
        `Invalid release binaries manifest entry ${index + 1} ('${entry['name']}'): 'repo' must be in 'owner/name' form.`,
      );
    }
    return {
      name: entry['name'],
      repo: entry['repo'],
      tag: entry['tag'],
      private: entry['private'],
    };
  });
  requireUniqueBy(
    binaries,
    (binary) => binary.name.toLowerCase(),
    `Release binaries manifest ${path}`,
  );
  return binaries;
}

function requireLockString(
  record: Record<string, unknown>,
  field: string,
  label: string,
): string {
  const value = record[field];
  if (typeof value !== 'string' || value.length === 0) {
    throw new ProvisioningError(
      `${label}: '${field}' must be a non-empty string.`,
    );
  }
  return value;
}

export function parseReleaseLock(raw: string, path: string): ReleaseLock {
  const parsed = requireRecord(
    loadYaml(raw, path),
    `Release binaries lock ${path}`,
  );
  requireExactKeys(parsed, ['binaries'], `Release binaries lock ${path}`);
  if (!Array.isArray(parsed['binaries'])) {
    throw new ProvisioningError(
      `Release binaries lock must contain a binaries sequence: ${path}`,
    );
  }
  const binaries = parsed['binaries'].map(
    (entry: unknown, index: number): ReleaseLockEntry => {
      const label = `Invalid release binaries lock entry ${index + 1}`;
      if (!isRecord(entry)) {
        throw new ProvisioningError(`${label}: entry must be a mapping.`);
      }
      requireExactKeys(entry, ['name', 'repo', 'tag', 'assets'], label);
      const name = requireLockString(entry, 'name', label);
      const labeled = `${label} ('${name}')`;
      const repo = requireLockString(entry, 'repo', labeled);
      const tag = requireLockString(entry, 'tag', labeled);
      const assets = requireRecord(entry['assets'], `${labeled} assets`);
      const digests: Record<string, ReleaseDigest> = {};
      for (const [asset, value] of Object.entries(assets)) {
        if (!releaseArchitectures.some((arch) => asset === `${OS}-${arch}`)) {
          throw new ProvisioningError(
            `${labeled}: unsupported asset '${asset}'.`,
          );
        }
        const assetLabel = `${labeled} asset '${asset}'`;
        const digest = requireRecord(value, assetLabel);
        requireExactKeys(digest, ['sha256'], assetLabel);
        const sha256 = requireLockString(digest, 'sha256', assetLabel);
        if (!SHA256.test(sha256)) {
          throw new ProvisioningError(
            `${assetLabel}: sha256 must be 64 lowercase hexadecimal characters.`,
          );
        }
        digests[asset] = { asset: asset as ReleaseAssetKey, sha256 };
      }
      return { name, repo, tag, assets: digests };
    },
  );
  requireUniqueBy(
    binaries,
    (binary) => binary.name.toLowerCase(),
    `Release binaries lock ${path}`,
  );
  return { binaries };
}

/**
 * The reviewed digest for one binary and architecture. The lock entry must
 * match the manifest's name, repo, and tag exactly, so a retagged or relocated
 * release never inherits a stale digest.
 */
export function resolveReleaseDigest(
  binary: ReleaseBinary,
  arch: ReleaseArch,
  lock: ReleaseLock,
): ReleaseDigest {
  const entry = lock.binaries.find(
    (candidate) =>
      candidate.name === binary.name &&
      candidate.repo === binary.repo &&
      candidate.tag === binary.tag,
  );
  if (!entry) {
    throw new ProvisioningError(
      `Release lock is missing ${binary.name} ${binary.tag} (${binary.repo}). Run 'bun run lock'.`,
    );
  }
  const asset = `${OS}-${arch}` as const;
  const digest = entry.assets[asset];
  if (!digest) {
    throw new ProvisioningError(
      `Release lock is missing the ${asset} digest for ${binary.name} ${binary.tag}. Run 'bun run lock'.`,
    );
  }
  return digest;
}

// macOS-only CLI, so the OS segment of every release asset name is fixed.
const OS = 'darwin';

const ARCH_BY_MACHINE: Readonly<Record<string, ReleaseArch>> = {
  x86_64: 'x86_64',
  arm64: 'aarch64',
};

/** Resolve the running machine's architecture as a GitHub release asset segment. */
export async function detectArch(context: Context): Promise<ReleaseArch> {
  const result = await runProcessStep(
    context.commands,
    'uname',
    ['-m'],
    'uname -m failed',
  );
  const machine = result.stdout.trim();
  const arch = ARCH_BY_MACHINE[machine];
  if (!arch) {
    throw new ProvisioningError(
      `Unsupported architecture '${machine}'. Expected one of: ${Object.keys(ARCH_BY_MACHINE).join(', ')}.`,
    );
  }
  return arch;
}

/** SHA-256 of the file at `path`, or null when it does not exist. */
export async function fileSha256(path: string): Promise<string | null> {
  let bytes: Uint8Array;
  try {
    bytes = await readFile(path);
  } catch (error) {
    if (isNotFound(error)) return null;
    throw error;
  }
  return createHash('sha256').update(bytes).digest('hex');
}

/**
 * Whether the binary already at `dest` has the reviewed bytes and execute
 * permission declared by the lock, the idempotency signal that skips a
 * re-download. A missing binary is the common first-run case and counts as not
 * installed; other read errors surface. When the content matches but the
 * execute bit was stripped (e.g. a backup restore), the mode is repaired in
 * place so a full re-download is unnecessary.
 */
export async function installedMatches(
  dest: string,
  digest: ReleaseDigest,
): Promise<boolean> {
  if ((await fileSha256(dest)) !== digest.sha256) return false;
  const mode = (await stat(dest)).mode;
  if ((mode & 0o111) === 0) {
    await chmod(dest, mode | 0o755);
  }
  return true;
}

/**
 * Download the release asset `<name>-<os>-<arch>` for `binary`, verify it
 * against the locked digest, and install it into `dest` marked executable.
 * Private repositories require an authenticated `gh release download`; public
 * ones are fetched anonymously over HTTPS. A digest mismatch throws before the
 * downloaded file can replace `dest`, so unreviewed bytes never land.
 */
export async function fetchReleaseBinary(
  binary: ReleaseBinary,
  arch: ReleaseArch,
  digest: ReleaseDigest,
  dest: string,
  context: Context,
): Promise<void> {
  const asset = releaseAssetName(binary, arch);
  await replaceFileAtomically(dest, async (tmp) => {
    if (binary.private) {
      await runProcessStep(
        context.commands,
        'gh',
        [
          'release',
          'download',
          binary.tag,
          '--repo',
          binary.repo,
          '--pattern',
          asset,
          '--output',
          tmp,
          '--clobber',
        ],
        `gh release download failed for ${binary.name}`,
      );
    } else {
      const url = `https://github.com/${binary.repo}/releases/download/${binary.tag}/${asset}`;
      await downloadOverHttps(context.commands, url, tmp, binary.name);
    }
    const actual = await fileSha256(tmp);
    if (actual !== digest.sha256) {
      throw new ProvisioningError(
        `Digest mismatch for ${binary.name} ${digest.asset}: expected ${digest.sha256}, got ${actual}.`,
      );
    }
    await chmod(tmp, 0o755);
  });
}
