alias ms-t='mise trust'
alias ms-p='mise prepare'
alias ms-ls='mise ls'
alias ms-ls-r='mise ls-remote'
alias ms-i='mise install'
alias ms-i-l='mise install --locked'
alias ms-lk='mise lock'
alias ms-e='mise exec --'
