import { createHash } from 'node:crypto';
import { stat } from 'node:fs/promises';
import { join } from 'node:path';
import { Glob } from 'bun';

const assetsRoot = join(import.meta.dir, '..', 'src', 'assets');
export const filesRoot = join(assetsRoot, 'config');
export const registryFile = join(assetsRoot, 'registry.generated.ts');

export interface AssetEntry {
  readonly key: string;
  readonly content: string;
  readonly executable: boolean;
}

async function readTextAsset(key: string): Promise<string> {
  let bytes: Uint8Array;
  try {
    bytes = await Bun.file(join(filesRoot, key)).bytes();
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to read asset '${key}': ${detail}`);
  }
  try {
    // Reject non-UTF-8 rather than silently embedding replacement characters:
    // the registry stores text assets only.
    return new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  } catch {
    throw new Error(
      `Asset '${key}' is not valid UTF-8. The codegen embeds text assets only; convert or remove it.`,
    );
  }
}

/** Walk the config tree into sorted, content-loaded asset entries. */
export async function collectAssets(): Promise<AssetEntry[]> {
  const glob = new Glob('**/*');
  const keys: string[] = [];
  for await (const path of glob.scan({
    cwd: filesRoot,
    onlyFiles: true,
    dot: true,
  })) {
    if (path === '.DS_Store' || path.endsWith('/.DS_Store')) continue;
    keys.push(path);
  }
  keys.sort();
  return Promise.all(
    keys.map(async (key) => {
      const content = await readTextAsset(key);
      const { mode } = await stat(join(filesRoot, key));
      return { key, content, executable: (mode & 0o100) !== 0 };
    }),
  );
}

/**
 * A content hash over the embedded asset set (keys, contents, and exec bits).
 * The generated registry embeds this so `validate-assets` can detect a stale
 * registry produced by a consumer that skipped the codegen pre-hooks.
 */
export function assetSourceHash(entries: readonly AssetEntry[]): string {
  const canonical = entries.map((entry) => [
    entry.key,
    entry.content,
    entry.executable,
  ]);
  return `sha256:${createHash('sha256').update(JSON.stringify(canonical)).digest('hex')}`;
}

/** Render the generated registry module body from the collected asset entries. */
export function renderRegistry(entries: readonly AssetEntry[]): string {
  const contents = entries
    .map(
      (entry) =>
        `  ${JSON.stringify(entry.key)}: ${JSON.stringify(entry.content)},`,
    )
    .join('\n');
  const executable = entries
    .filter((entry) => entry.executable)
    .map((entry) => `  ${JSON.stringify(entry.key)},`)
    .join('\n');
  const banner =
    '// Generated by scripts/generate-assets.ts from src/assets/config/. Do not edit.';
  return `${banner}

export const registrySourceHash = ${JSON.stringify(assetSourceHash(entries))};

export const assetContents: Record<string, string> = {
${contents}
};

export const executableAssets: readonly string[] = [
${executable}
];
`;
}
