/**
 * Generates `src/assets/registry.generated.ts` by walking the config
 * tree under `src/assets/config/`. Each file's content is inlined as a
 * string keyed by its path relative to that root, so the compiled binary
 * embeds every asset without per-file imports or filesystem access at runtime.
 * A file whose source carries the owner-execute bit is also listed in
 * `executableAssets` so deployment restores that bit; scripts invoked directly
 * (statusline commands) need it.
 *
 * The asset directory is the single source of truth: adding a feature's files
 * regenerates the registry without hand-editing any enumeration.
 */

import { stat } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { Glob } from 'bun';

const assetsRoot = join(import.meta.dir, '..', 'src', 'assets');
const filesRoot = join(assetsRoot, 'config');
const outFile = join(assetsRoot, 'registry.generated.ts');

const glob = new Glob('**/*');
const keys: string[] = [];
for await (const path of glob.scan({
  cwd: filesRoot,
  onlyFiles: true,
  dot: true,
})) {
  keys.push(path);
}
keys.sort();

const entries = await Promise.all(
  keys.map(async (key) => {
    const content = await Bun.file(join(filesRoot, key)).text();
    return `  ${JSON.stringify(key)}: ${JSON.stringify(content)},`;
  }),
);

const executable = await Promise.all(
  keys.map(async (key) => {
    const { mode } = await stat(join(filesRoot, key));
    return (mode & 0o100) !== 0 ? key : null;
  }),
);
const executableEntries = executable
  .filter((key): key is string => key !== null)
  .map((key) => `  ${JSON.stringify(key)},`);

const banner =
  '// Generated by scripts/generate-assets.ts from src/assets/config/. Do not edit.';
const body = `${banner}\n\nexport const assetContents: Record<string, string> = {\n${entries.join('\n')}\n};\n\nexport const executableAssets: readonly string[] = [\n${executableEntries.join('\n')}\n];\n`;

await Bun.write(outFile, body);
console.log(
  `Generated ${relative(process.cwd(), outFile)} (${keys.length} assets, ${executableEntries.length} executable).`,
);
