alias u="uv"
alias u-ini="uv init"
alias u-py="uv python"
alias u-py-i="uv python install"
alias u-py-ls="uv python list"
alias u-py-p="uv python pin"
alias u-v="uv venv"
alias u-a="uv add"
alias u-s="uv sync"
alias u-b="uv build"
alias u-s-e="uv sync --extra"
alias u-s-nd="uv sync --no-dev"
alias u-s-og="uv sync --only-group"
alias u-lk="uv lock"
alias u-rv="py-cln;u-v;u-s"
alias u-r="uv run"
alias u-e="uv export --format requirements.txt > requirements.txt"
alias u-cln="rm -rf ~/.cache/uv"

# uvx
alias ux="uvx"
alias ux-c="uvx cowsay -t"
