# Test Workflow
#
# Runs Bun tests.

name: Run Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-tests:
    name: Run ${{ matrix.type }} tests
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        type: [unit, integration]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Development Environment
        uses: ./.github/actions/setup

      - name: Run ${{ matrix.type }} tests
        run: bun run test:${{ matrix.type }}
